### ISSUE TITLE
Query issue

### ISSUE THREAD

**Issue by cakesoft-yash** [simonw/covid-19-datasette#13]
select * from johns_hopkins_csse_daily_reports where country_or_region='US';
I tried to hit this query but not getting all the data.
Thank you.

**Comment by simonw** [comment]
You need pagination, which isn't supported on the query page. You can paginate here:

https://covid-19.datasettes.com/covid/johns_hopkins_csse_daily_reports?country_or_region=US

That page also offers an option to export ALL matching rows as CSV - https://covid-19.datasettes.com/covid/johns_hopkins_csse_daily_reports?country_or_region=US#export - check the "stream all rows" button.
